### ISSUE TITLE
Saiyans/Namekians/Whatever crawl and swim very, very slowly.

### ISSUE THREAD

**Issue by Alceris** [Putnam3145/SPARKING-Dwarf-Fortress-DBZ-mod#18]
That's, uh, that's it. Not really much else to say. It's because they don't have crawling or swimming speeds set.

**Comment by Putnam3145** [comment]
They shouldn't be swimming slowly, since they actually do have a swim speed, but yeah, forgot a crawl gait.

**Comment by Putnam3145** [comment]
Fixed by d0d35ff17d33e84a8943750bd52a6662a79d9724
