### ISSUE TITLE
Permanently Super Saiyan

### ISSUE THREAD

**Issue by Alceris** [Putnam3145/SPARKING-Dwarf-Fortress-DBZ-mod#21]
What more is there to say? I'm just stuck in Super Saiyan form.

**Comment by Alceris** [comment]
For some reason, it was because of the flashing tile effect I added.

**Comment by Putnam3145** [comment]
I had this issue with an individual who ended up permanently in Super Saiyan 2; she was my Super Saiyan God, too, so she ended up pretty silly.

AFAIK, it's a syndrome issue, meaning I can't much do anything about it. She didn't actually have the ki boost from SS2 either, just the misc. effects. It was strange.

**Comment by Alceris** [comment]
I am actually getting the Ki boost from it, permanently, and neither sleeping nor fast-traveling will get rid of it like it has before. So, am I just screwed and have to create a new world, then?

**Comment by Putnam3145** [comment]
Haven't seen another case of this since--closing, will reopen if shows up again
