### ISSUE TITLE
Majins can be strangled to death. (not sure if intentional)

### ISSUE THREAD

**Issue by Alceris** [Putnam3145/SPARKING-Dwarf-Fortress-DBZ-mod#22]
Again, pretty self-explanatory titles.

**Comment by Putnam3145** [comment]
https://github.com/Putnam3145/SPARKING-Dwarf-Fortress-DBZ-mod/commit/26297575e621c83d29545f542e7614597b3b1e0d

That commit should fix it; this is a fairly simple fix in-game. It's a bit late for testing, so I'll test the cutting edge, fix any bugs that I can find and try to release ASAP.

**Comment by Putnam3145** [comment]
that did fix it, i just never bothered testing, shouldn't need testing anyway
