### ISSUE TITLE
Ki doesn't provide as much of a boost in attack force as it should. (Cutting Edge)

### ISSUE THREAD

**Issue by Alceris** [Putnam3145/SPARKING-Dwarf-Fortress-DBZ-mod#26]
In Master, if you punched a normal human in the head as a Super Saiyan, their head would explode and they would fly through the air. In Cutting Edge, at best, it collapses into a lump of gore on a direct hit, and usually just causes skull fractures.

**Comment by Alceris** [comment]
Actually it might be that the Super Saiyan form isn't providing any actual boost in Ki. This is strange.

**Comment by Putnam3145** [comment]
14a396a ought to have fixed this. Keeping the issue open in case it didn't.

**Comment by Putnam3145** [comment]
it did
