### ISSUE TITLE
Cannot read field unit.T_counters2.endurance: not found.

### ISSUE THREAD

**Issue by Alceris** [Putnam3145/SPARKING-Dwarf-Fortress-DBZ-mod#41]

**Comment by Alceris** [comment]
There was supposed to be an attached image, but I have no idea if that worked.

**Comment by Putnam3145** [comment]
fixed with https://github.com/Putnam3145/SPARKING-Dwarf-Fortress-DBZ-mod/commit/5684f83f65413769874db6ce60c688090024e597
